"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy": true

"files": [
    {
      "source": "src/lang/extracted/*.json", #source files filter
      "translation": "src/lang/translated/%locale%.json", #where translations are stored
    },
  ]
