name: Download translations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Once a day - https://crontab.guru/#0_0_*_*_*

permissions:
  contents: write
  pull-requests: write

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v1.15.2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: "New Crowdin Translations"
          pull_request_body: "New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)"
          pull_request_base_branch_name: "main"
          preserve_hierarchy: true
          source: "src/lang/extracted/en-US.json"
          translation: "src/lang/compiled/%locale%.json"
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
