name: Download translations

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Once a day - https://crontab.guru/#0_0_*_*_*

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Download translations
        uses: crowdin/github-action@v1.15.2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          create_pull_request: false
          push_translations: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Compile translations
        run: find ./src/lang/translated -maxdepth 1 -iname '*.json' -exec sh -c 'npm run compile -- "{}" --out-file "./src/lang/compiled/$(basename {})"' \;

      # - name: "Commit translation changes"
      #   run: |
      #     sudo chown $(whoami) -R .git/
      #     git config user.name ${{ github.actor }}
      #     git config user.email ${{ github.actor }}@users.noreply.github.com
      #     git add ./src/lang/
      #     git commit -m "Add new Crowdin translations"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          committer: GitHub Action <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: l10n_crowdin_translations
          delete-branch: true
          title: "New Crowdin translations"
          body: "New Crowdin pull request with translations"
