name: Upload translations

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Extract translations
        run: npm run extract

      - name: crowdin action
        uses: crowdin/github-action@v1.15.2
        with:
          upload_sources: true
          upload_translations: true
          download_translations: false
          source: "src/lang/extracted/en-US.json"
          translation: "src/lang/compiled/%locale%.json"
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
